# Notes---an agenda for research on long-term imprisonment

After a quiet period on the blog while I've been working on other things, this will be the first in a series of posts which are essentially notes on the reading I've been doing. Other posts will specifically be written for the blog, but these notes posts are a way of trying to force myself into some writing, and also to share some of what I'm doing.

This is on an article I've re-read recently, which sets out an agenda for far greater attention by criminologists and policymakers to the needs of long-term prisoners. The citation is at the end.

Kazemian and Travis set out the case that there should be a far greater attention to long-term and life-sentenced prisoners as a group. Their argument particularly draws on the US context, but is relevant to the UK as well, because of the high numbers of lifers that we imprison.

## Lifers and long-termers as a largely ignored group

The case made here is that long-termers and lifers have been 'largely ignored' (p.357) as a group when it comes to research on desistance from crime. Some of the reasons for this are technical, and are connected with how hard it is to design longitudinal research that can follow people for long enough as well as controlling for the effects of what are often very different prison environments.

But Kazemian and Travis argue that the other reasons for the neglect of long-term prisoners are political. Because lengthy prison sentences are often assumed to be given to the 'worst of the worst' offenders, who are unpopular and lack any form of representation, the needs of long-sentenced prisoners have been easy to ignore and sideline, and have tended therefore to be a low political priority. Moreover, it is widely noted among prison administrators and researchers that the majority of lifers are highly compliant, adding to the impression that their needs can be forgotten. As a result, there is a dearth of interventions specifically addressing their needs, and those which are available sometimes fail to recognise what is unusual about their situation, and how they may have become quite different people to when they were first imprisoned, without a great deal of deliberate rehabilitative input from the prison authorities. This last point rings very true for me, tallying with what I was told by a couple of the men I interviewed in 2017 while doing my pilot research for this project.

## What is the current state of research?

Most of the major studies of long-term prisoners as a group are out of date: they were conducted in the 1970s and 80s, mostly in the US and the UK. These studies are of limited help when it comes to thinking about imprisonment today: although they offer some pointers about the effects of imprisonment on the individual, imprisonment itself has changed: prisons are usually more overcrowded, larger, and more ethnically and culturally diverse, sentences are longer, and the expectations placed on prisoners different. Despite its limitations, the available research offers some pointers, suggesting that long-term and life-sentenced prisoners, as a group:

-   face distinctive challenges and have distinctive needs, arising from the fact that such a large part of their life will be spent in prison, distorting the 'normal' life course
-   pose no greater risk of harm to others (either within prison or after release) than short-term prisoners
-   reoffend at far lower rates than short-term prisoners

In addition, it appears that:

-   longer sentences don't result in better outcomes, with time served a poor predictor of recidivism
-   most long-termers find imprisonment very difficult but find ways to cope
-   that the changes they undergo are poorly understood and may be unhelpful when it comes to life after release. Specifically, and in general:
-   people get less dangerous as they get older
-   this does not mean they are well-prepared for life after prison; for that to happen, prison regimes have to be deliberately planned towards that outcome

There is also good evidence, in general, that some prison environments are more harmful than others. A well-run prison can achieve better outcomes, but a negative one can make it far harder to survive, with bad prisons significantly increasing outcomes such as suicide, violence and self-harm.

## Are prisons good? Or bad? Or something else?

For me some of the most interesting parts of the case that Kazemian and Travis put forward relate to how we evaluate imprisonment as a whole. There are two distinct points here.

First, in the US, at least, the debate over mass incarceration has hampered our understanding of how to make prisons better places. Two antagonistic ways of looking at prisons have taken hold:

-   one emphasises that prisons incapacitate dangerous people for a period of time, and thereby benefit everyone else outside
-   another emphasises that prisons don't reduce reoffending as much as other interventions, and thereby fail to benefit everyone else outside

The authors point out that these are both valid positions but each answers a rather different question. As a result, the debate has hardened into two opposed camps emphasising different evaluations, and thus has become bogged down in polarised debate over whether prisons are either 'good' or 'bad'. In fact, neither position captures the intricacies of how people experience their sentences, nor the complexity of the consequences. More importantly, the antagonistic nature of the debate limits understanding of how to achieve better outcomes. This is especially important in the case of long-term imprisonment for serious offences, when the available alternatives to imprisonment are few or none.

## But do long prison sentences *work*?

Second, Kazemian and Travis argue that both of the views above are really questions about how the wider community does or does not benefit from imprisonment, and say nothing of the prisoner's experience. For example, in focusing too narrowly on reoffending rates and other outcomes after release, we risk endorsing the view that these are the only outcomes that matter. They measure only whether imprisonment benefits the wider community, not whether it might benefit (or harm) long-term prisoners themselves, in ways that are slow, incremental and less straightforward to observe, nor whether these individual-level changes benefit or harm others:

\*"A recidivism-focused approach disregards changes and progress exhibited in other behavioral, cognitive, and social outcomes. Studies have found that criminal careers are characterized by a great deal of intermittency, and several researchers have acknowledged the relevance of perceiving desistance \[from crime\] as a gradual process" (p.377) \*

Another to think about this is to ask whether the ends always justify the means. If lifers seldom reoffend, but they were kept in prison longer than was necessary to achieve that outcome, and meanwhile their families and communities suffered by their absence, does that matter?

Kazemian and Travis point out that this question gains particular purchase in the context of the US imprisonment binge of the last 40 years: the impacts on ethnic and racial minority communities of mass imprisonment have been disastrous, and most of those harmed committed no offence. They quote research by Johnson and McGunigall-Smith, who conclude that lifers are:

-   'manageable prisoners, \[even\] model prisoners, but their decent adjustment does not change the fact that their lives are marked by suffering and privation.'

(quoted p.383) \*

## Thankful for one's imprisonment?

The idea that the debate on prisons has become narrow and polarised rings true to me. The dualistic view doesn't tally with the complexity of what I have heard from lots (though not all) of the long-term prisoners I've met over the years: that for all that being in prison has been bad, it's somehow enabled positive change. Here is one of the men I interviewed for my MPhil research:

\*'I have to thank \[prison\], in a way \[...\] This place has changed a lot since I came here seven years ago, not all for the best, mostly it's just down, but... \[long pause\] This place changed me, you know? I have emotional ties here. I will always be thankful. It is like a dysfunctional home to me.' 'David' (not his real name)\*

This definitely does not represent everyone's experience of long-term imprisonment, but it is some people's, and that matters. I think the 'I will always be thankful' has to be taken seriously. I also think that this is not the same as saying imprisonment is *a good thing* (or that it *works*, or that we should have more of it). It recognises that, at least in the case of serious offences, imprisonment has been an unavoidable response to serious harm, and that in these circumstances it might make sense to try and ensure that it does no more harm in return than is necessary. 'David' certainly seemed to me to mean what he said, and from what he said it also seemed that he had coped and adapted well. It should also be noted, however, that he was relatively near to the end of his sentence. Whether, in a few years' time and with the benefit of future hindsight, he would have said the same after release is another question.

## Lifers as leaders

Kazemian and Travis go on to make the case that long-termers should be seen as potential leaders and mentors in the prison environment. They argue that prisons should make long-term planning of this kind part of the sentence plan, rather than leaving sentence planning to work on the same basis as it does for shorter sentences.

They go on to say that it's possible that this may already be happening, that in other words:

'long termers and lifers are already contributing to the enhancement of the prison community, but to our knowledge, virtually no data (other than anecdotal) exist to verify this claim'

*p.372*

My hunch, based my experience working in prisons, and also on [some recent research I've read](https://dx.doi.org/10.1177/1748895818800743), is that a lot of the social interactions in which long-termers could be exercising leadership in this way occur in the everyday social life of the prison: on the wings, in the workshops, in education classrooms, and so on, and not just in formal, officially-organised rehabilitative interventions such as offending behaviour courses. This means that significant amounts of personal change could be taking place in the same locations, but that how this happens is not well understood. This is the kind of ground-level research question that ethnographic research is good at illuminating.

## Summary

Kazemian and Travis call for more attention by criminologists and policymakers to how imprisonment can be designed around the needs of lifers, and how they can be invested in as a resource; primarily this argument is made based on what K&T see as in their interests, but as they argue, this stands to benefit others as well.

I find their case persuasive, and it's similar to a case that a group of charities I worked with some years ago tried to put to the Prison Service. It goes without saying that it's a reformist rather than an abolitionist position regarding imprisonment itself, and I think it needs to be coupled with due interest and regard to what lifers themselves want from prison regimes.

