---
title: 'Not just a piece of cake'
author: Ben Jarman
date: 2019-08-19
lang: en-GB
categories: [blog post, changing inside]
description: On why hospitality in prison can mean rather more than it does elsewhere, and why a piece of cake isn’t just a piece of cake.
---

Earlier this year I was involved in a project at a high-security prison. Each week a group of students from my university went into the prison to hear a course of lectures alongside a group of students resident in the prison. You can read more about the project [here](https://www.learningtogethernetwork.co.uk/about-us/). I think it was around the fourth week of the course that something surprising happened: the students who lived in the prison began to turn up to the classes with cakes, which they had baked to share in the tea break after each lecture, before our small group discussions began. The sharing of cake continued for the remainder of the course, with the cakes getting more and more elaborate over time. A little bit of competition crept in, with some of the men from different wings trying to outdo one another: cakes topped with tinned mango and pineapple, profiteroles, lemon drizzle---you name it. It was a welcome and unexpected addition to the course experience, and it restored a certain normality to our days in the prison, each of which began with queueing to be frisked, searched, and led through gates and heavy doors on the way in.

## Is anything actually surprising here?

On one level, there's nothing unusual about food being prepared and shared with guests: it's a key element of hospitality and sociability, and really quite an unremarkable thing. Even so, I was surprised. Not just *that* the cakes had been made: long-term prisons often have cooking facilities, though I also appreciated that laying on that *quantity* of baking represented a significant material outlay for the men: prison work is not well-paid by outside standards and they had been buying the ingredients themselves. Instead, what really surprised---and impressed---me was that the prison had given permission for the cakes to be brought all the way from the wings to the classroom. In all the time I've worked in prisons, I've never been welcomed with hospitality of this kind, and not, I suspect, because no one wanted to offer it.

High-security prisons can be dangerous places, though very rarely for visitors like us. Some weeks, during the the usual 'how-are-you' conversations that preceded each lecture, some of the men described tensions and incidents on the wings. These descriptions were a useful reminder that whatever was happening in the classroom, this was still a prison: a challenging, difficult place to live. Mistrust and suspicion are to a certain extent institutionalised, often for good reason. Quite apart from the fact that the cakes were pretty good to eat, it impressed me that someone in the prison had decided to recognise the baking as an ethical practice---an attempt to realise values of hospitality and conviviality, and of treating guests well---rather than to forbid it as a potentially crafty attempt to smuggle out contraband or manipulate the naïve university students.

## Too much security? Or the wrong kind?

That description of a certain security mindset might sound like an exaggeration, but it's really not: risk aversion and security thinking, as well as being necessary, can also, if unchecked or unchallenged, lead to some bizarre situations, including the famous (to prison scholars!) example of a ['subversive geranium'](https://www.jstor.org/stable/590661?origin=crossref). It can also lead to outcomes that are subtly but profoundly dehumanising: a tendency to view *everything*that prisoners do as [potentially risky](http://doi.wiley.com/10.1111/1468-4446.12310), and consequently a situation in which quite normal human practices like hospitality or food-sharing are shut down on the grounds of potential danger.

Ryan Williams has [written about this](https://academic.oup.com/bjc/article-abstract/58/3/730/3862715) in relation to 'prison Islam'---or as he pointedly calls it, Islamic piety. His research describes how certain visible markers of piety---such as beards, traditional Muslim dress, and so on---came to be read by prison authorities as evidence of potential radicalisation, and hence as a reason to treat those who bore them with greater-than-normal suspicion. It must be difficult to get out of these cycles of thinking. Prison culture often has strong them-and-us overtones: for a prisoner to be seen as too close to the staff can be costly (and the reverse can also be true). Normal human communication about the *meaning* of dress or beard-wearing can be difficult, and trust breaks down as a result. For prisoners, this can lead to the feeling that one is constantly watched but also constantly misrecognised: power feels very distant and uncaring, unerring suspicion of one's attempts to be and do good feels like a slight, and keeping hope and making progress begin to seem impossible as the trap closes in. Extended over the decades-long sentences that serious offences mostly now attract, the effect can be counterproductive and feel illegitimate.

## The practice of ethics

I've chosen the topic of cake for this post---and what seemed to me a wise decision by the prison to allow it to be brought to the classes---because I'm going to be starting my own prison fieldwork pretty soon, and posts on this blog will get a bit more frequent. This question of ethics---of what it means to try and conceive of and live a 'good life', especially when you live under significant constraint---has become one of the major topics I'm interested in, and will be one of the things I'm thinking and writing about while I do my fieldwork.

Anthropologists have done a lot of work in the last 15 or 20 years on how to study and make sense of ethics as an empirical phenomenon---that is, as a set of practices in the real world, rather than as a set of abstractions about what is the right thing to do in theory. Scholars in the field have tried to move away from the idea that morals are just preferences, with no greater importance for human behaviour than others such as preferred colour. They also insist that they can be studied in the real world, and subjected to rational discussion.

## Balancing competing values

Reading anthropological texts on this subject has helped sharpen my ideas about what to think and ask about when I'm doing my prison fieldwork. One key insight is that doing good means neither *the "correct and deliberate following of rules", *nor\* having "the courage or insight to ignore, subvert, transcend, or reinvent" rules (Lambek 2018: 139). Instead, it means having the capacity to recognise that sometimes rules and principles are in tension, and that different dimensions of value bear on the same issue. There are good reasons not to allow items like cakes to move around the prison; but applying these rules excessively can squash other things that are valuable too. Sometimes, this calls for rules to be challenged, bent, or suspended in favour of others, and that means ethical action also involves some degree of risk. In the suspicious environment described above, simply asking to bring a cake opens one to a degree of scrutiny; and permitting it to be brought cedes some amount of control over the way in which the class takes place. Ethics, then, involves a certain quality of practical judgment: having the capacity to choose, and to choose wisely, among the different sets of rules and principles and values that might apply to a given situation. Sometimes these judgments are habitual and automatic; sometimes they are deliberate and reflective; but always they are contestable and uncertain. We can't always predict outcomes.

We all live with rules and constraints around us, and we all make judgments in relation to them all the time: prisons merely represent a place in which rules and constraints are present to an unusually intense degree. They are also places where disparities in power are enormous, and institutionalised. Being powerful or powerless doesn't make you more or less ethical, however, and being ethical isn't a static state: instead, you're always in the process of *becoming*. Being mistaken, making decisions without access to all relevant facts, and getting things wrong are all more or less inevitable, which is why ethics can also sometimes be tragic: we can sometimes do wrong despite a sincere belief that we are doing right. Sometimes hindsight is not a wonderful thing at all. In the right conditions, though---if we can take for granted our basic safety and security, and if we're able to reflect on ourselves---we can also learn, and re-evaluate ourselves, and perhaps even shape ourselves into something else than what we have been before.

## Returning to prisons

By now the relevance for prisons of this way of thinking should be clear. About prisons, we already have [the empirical finding](https://doi.org/10.1080/07418825.2016.1190394) that long-term prisoners commonly take up conscious and deliberate projects of self-improvement, searching for a "cause, vocation or ideal" (Crewe et al., 2017: 537) that helps make prison life less monotonous and more meaningful. [We also know](https://doi.org/10.1080/07418825.2018.1538421) that prisons which make it easier for prisoners to do this kind of work on the self---prisons which *are* physically safer places, and which use their power more legitimately---have significantly better outcomes: lower rates of suicide and self-harm, lower levels of distress, lower rates of reoffending. Readers familiar with criminology might also recognise some echoes from desistance research, particularly in the idea that people reflect on and reevaluate their values while subject to punishment.

What I'll be doing with this fieldwork is trying to zoom into how this all plays out at the micro-level of individual thought. I'll be interviewing men serving life sentences in depth about what 'being good' means to them: whether it's feasible; how they try to do it; how being convicted of different kinds of offence or serving time in different kinds of prison environments affects things; and whether and how 'being good' is recognised. It's not just going to be a PhD about cake; but the example shows that cake (like many other things) can signify a lot more than just hospitality.

