# New publication: A poor prospect indeed

Things have been quiet on here for the last month or two while I've been working on admin to do with the PhD -- ethics forms, risk assessments, and so on -- and while I've been preparing some past work for publication in an academic journal.

This post is just a quick one to publicise [that journal article](https://www.mdpi.com/2075-4698/9/2/27), by me and Caroline Lanskey, which was published today. It's based on historical research I carried out last year, before starting the PhD, with Caroline and other colleagues from Cambridge and the University of Edinburgh. We investigated what safeguards existed to try and prevent child abuse in youth prisons between 1960 and the present day, and how they changed. It's a grim topic, so I can't say that I'm delighted about publishing it. But I am proud of the work.

Youth custody in the past was often marked by extensive staff and inmate violence, and sometimes by sexual abuse. The issue became topical again while the article was being peer-reviewed: officers who worked there in the 1970s and 1980s [were themselves imprisoned](https://www.bbc.co.uk/news/uk-england-tyne-47965929) for historic abuse.

Our report to the Prison Service (which commissioned the research) [was published last year](https://www.repository.cam.ac.uk/handle/1810/287561). This newer journal article covers only the earlier period, and asks why the safeguards which were in place from 1960 to 1990 so comprehensively failed to prevent abuse.

The recent convictions, coming at a time where violence in youth prisons is [in the headlines](https://www.independent.co.uk/news/uk/home-news/feltham-yoi-jail-prison-officer-attack-fight-hospital-london-a8861061.html), and [inspectorates](https://www.justiceinspectorates.gov.uk/hmiprisons/inspections/children-in-custody-2017-18/) and [others](https://howardleague.org/our-campaigns/transform-prisons/children-and-young-people/) are expressing serious concerns about their safety, have reinforced contemporary calls for an [end to child imprisonment](https://article39.org.uk/endchildimprisonment/). We argue in the article that while the failures of the past (like those of today) have complex causes, now is a good time to be reflecting on them.
