# Welcome

Welcome to the Changing Inside blog. This site exists to share information about my PhD research. You can read more about me (Ben Jarman), the research, and its funders in the sidebar menu.

## What you will find on this site

I plan to use this site as a kind of online notebook, in which I record things I am reading, writing and thinking about as the project continues. For now this will mainly consist of ideas based on reading and project design, but once I start doing the fieldwork I will also post about that.

## Why life imprisonment?

Overall, the research focuses on life imprisonment, and specifically people serving mandatory life sentences for murder. Life sentences have been increasing, both in number and in length. There are now thousands of people serving life sentences who will be imprisoned for decades to come. This alone is a reason to think carefully about how such a heavy sanction is used against them, whether it is effective, justified, what kinds of challenges it poses, and so on.

But what the research is mostly interested in is how people's self-image --- who they think they are and who they want to become --- changes while they are serving very long prison sentences. This isn't currently very well understood: previous studies of long-term imprisonment shed some light on the issue, but because life sentences were shorter and prison conditions were very different when they were carried out, they are not always relevant to today's situation.

## What I'm trying to research

The title of the blog highlights the idea that people change while they are imprisoned, but also signals that my main interest is in how people's self-image change, and also whether and how this gets recognised by others. The research I am carrying out aims to fill some of the gaps I've just described. Among other things, it is interested in:

-   how prisoners experience their very long sentences
-   whether they perceive themselves to be morally stigmatised by their offending, and whether this feels permanent
-   whether they are interested in trying to become 'better' people (as opposed to, say, 'fighting the system') and what this means to them
-   whether the stage they are at in their sentence makes a difference
-   whether some murders are harder to 'move on' from than others
-   what this might mean for how long-term imprisonment should be thought about (and organised)

There are resources available to help with the task. Particularly, a rich body of recent criminological research into 'desistance' --- that is, how people change and 'desist from' (or move away) from criminality --- contains relevant theories and ideas. This research has not been applied much to the most serious offences, or to long-term imprisonment, but this project seeks to fill that gap. Since around the turn of the millennium, there has also been a great deal of anthropological research on 'ethical development', meaning 'how people (including those in very difficult circumstances) think about what a good life might be, and what they do as a result'. This second body of work is interesting because it helps to think about what it might mean to be a 'good' person when you're serving a long sentence in an institution created to hold 'bad' people. How do people hold those opposites in tension?

## Who the site is for

I am writing this blog to engage not only other academics, but also interested non-specialists. With that in mind I will be trying to keep my language relatively straightforward, and won't be writing in formal academic language and style. I will make clear the main texts I refer to, but generally won't post long lists of references. The research is [part-funded](https://changinginside.co.uk/about-the-funders/) by Quakers in Britain. This funding arrangement has not influenced the research questions or the methods, which were in place before the funding was secured. However, I am a Quaker, and the Quaker perspective on questions to do with imprisonment is therefore naturally interesting to me. There will be some posts on that topic, and this blog may be of particular interest to Quakers who are working in or around the criminal justice system.

## Summary

I want the site to make the closed world of long-term imprisonment more visible. There are certain constraints I have to follow --- for example, protecting the anonymity and safety of my research participants. I would prefer feedback on the contents of this blog to be courteous and constructive where possible. But I don't expect everyone reading this site to like or agree with what they find here, and I am genuinely interested to hear what people make of what's being posted here.

In general, posts on the site will be open for comments, though they will be moderated before they are published: please don't be offended if it takes a day or two for yours to appear (or for me to reply).

## Subscribe!

Sign up for email updates using the form below, or use the sidebar menu to find Twitter and Linked in links, as well as the RSS feed for the site.

------------------------------------------------------------------------

