---
abstract: >
  Why have prison scholars so seldom discussed what people in prison think about their crimes? This article addresses a striking gap: the omission of the offence—the originating reason for incarceration—from sociological analyses of carceral life. We discuss how and why the offence has featured in past prison scholarship, and argue for its recentring in future. Using three case studies, we show that the offence is not simply the reason people enter prison but can be an active force shaping daily experience, institutional engagement, and social dynamics. We propose a framework to examine how the offence illuminates what prisons are like to experience, what they attempt to do through moral communication, and what they are for, as places of punishment. Our analysis suggests that while prisoners may share the “same island”, they arrive there in fundamentally “different boats” of moral meaning—and that attending to the offence can enrich our understanding of adaptation, compliance, and legitimacy.
  
authors:
  - id: bmhj
    name:
      given: Ben
      family: Jarman
      literal: Ben Jarman
    attributes:
      corresponding: true
    email: ben@benjarman.uk
    orcid: 0000-0003-3527-5437
    url: https://benjarman.uk
    affiliation:
      - ref: soton
    role: >
      This article builds from conversations which developed over several years. We would find it difficult to specify precisely which author contributed which parts of the argument, and all authors contributed equally overall. Author names appear in reverse alphabetical order by surname, to avoid replicating academic seniority based on the alphabetical positioning of our surnames.
  - id: amani
    name:
      given: Alice
      family: Ievins
      literal: Alice Ievins
    attributes:
      corresponding: false
    email: aievins@liverpool.ac.uk
    orcid: 0000-0003-1945-3395
    url: https://www.liverpool.ac.uk/people/alice-ievins
    affiliation:
      - ref: liv
    role: >
      This article builds from conversations which developed over several years. We would find it difficult to specify precisely which author contributed which parts of the argument, and all authors contributed equally overall. Author names appear in reverse alphabetical order by surname, to avoid replicating academic seniority based on the alphabetical positioning of our surnames.
  - id: bc
    name:
      given: Ben
      family: Crewe
      literal: Ben Crewe
    attributes:
      corresponding: false
    email: bc247@cam.ac.uk
    orcid: 0000-0002-5296-5475
    url: https://www.crim.cam.ac.uk/People/professor-ben-crewe
    affiliation:
      - ref: cam
    role: >
      This article builds from conversations which developed over several years. We would find it difficult to specify precisely which author contributed which parts of the argument, and all authors contributed equally overall. Author names appear in reverse alphabetical order by surname, to avoid replicating academic seniority based on the alphabetical positioning of our surnames.

affiliations:
  - id: soton
    name: University of Southampton
    department: Southampton Law School
    group: Centre for Justice Studies
    address: University Road
    city: Southampton
    postal-code: SO17 1BJ
    country: United Kingdom
    url: https://www.southampton.ac.uk/about/faculties-schools-departments/southampton-law-school
  - id: liv
    name: University of Liverpool
    department: Department of Sociology, Social Policy, and Criminology
    address: |
      School of Law and Social Justice Building
      Chatham Street
    city: Liverpool
    postal-code: L69 7ZR
    country: United Kingdom
    url: https://www.liverpool.ac.uk/sociology-social-policy-and-criminology/
  - id: cam
    name: University of Cambridge
    department: Institute of Criminology
    group: Prisons Research Centre
    address: Sidgwick Avenue
    city: Cambridge
    postal-code: CB3 9DA
    country: United Kingdom
    url: https://www.crim.cam.ac.uk

title: "\"Same island, different boat\""
subtitle: "Why, and with what effects, has prison sociology ignored the offence?"
date: last-modified
categories: # select from the following
  - journal article
# description:

funding: >
  This work was supported by the UK Economic & Social Research Council via grants ES/J007935/1 and ES/T005459/1, and PhD studentship 2405252 under grant ES/P000738/1 (the latter co-funded by Quakers in Britain who played no part in the design of the study or the analysis and interpretation of data); and by the European Research Council via grant 648691).

keywords:  
  - prison sociology
  - moral communication
  - punishment
  - prison ethnography
  - legitimacy
  - adaptation
lang: en-GB
# doi: 
# url: 
license: CC BY-NC-SA 4.0
copyright:
  holder: The Authors
  year: 2025
draft: true
toc: true
toc-depth: 2
bibliography: jarmanSameIslandDifferent2025.yaml
citation: true
---

# Introduction

Prison scholarship has often implied that *why* people are incarcerated---what they have done or are deemed to have done---has no relevance to the internal dynamics of the institutions on which it focuses. Certainly, the classic texts of prison sociology tended to approach the prison as an organisation whose form is analogous to other organisations with purposes unrelated to punishment (by which we mean the intentionally denunciatory and pain-inflicting response to legally determined criminal wrongdoing). The most obvious example is *Asylums* [@goffmanAsylumsEssaysSocial1961], which bundles prisons with monasteries, boarding schools and military barracks as examples of “total institutions”. *The Society of Captives* [@sykesSocietyCaptivesStudy1958, p. xiv] likewise understands the prison as a social system principally organised “to create and maintain total or almost total social control”. Given the period when Sykes was writing, the parallels he draws with concentration camps and gulags are apt. Yet it means that the prison’s task *as a site of punishment* is largely bracketed off from his subsequent analysis. Foucault’s *Discipline and Punish* places punishment centre-stage, but is not really about prisons, so much as what their techniques tell us about a more extensive reorganisation of power around panoptic surveillance and the cultivation of selfhood. “Is it surprising”, Foucault [-@foucaultDisciplinePunishBirth1995, p. 9] asks, “that prisons resemble factories, schools, barracks, hospitals, which all resemble prisons?”. In all such studies, then, the prison is presented as a somewhat generic institution, rather than one with a distinctive purpose or culture, linked to the reasons why people are confined within them.

The effect of relegating punishment beneath concerns about power, control and discipline is to neglect one of the prison’s most fundamental characteristics. Because people are sent to them as punishment, and often seek to make sense of, or amends for, the acts or convictions that put them there [@irwinLifersSeekingRedemption2009; @schinkelBeingImprisonedPunishment2014; @herbertTooEasyKeep2019], prisons are permeated by moral concerns. Indeed, in many jurisdictions, they were designed to encourage moral reflection, an objective which unified their aims, architecture and regimes [@odonnellAimsImprisonment2016]. In other words, the offences that accounted for people being incarcerated were once absolutely central to how prisons functioned. In recent decades, however, discourses of penal administration have shifted, obscuring the offence’s relevance. Running prisons has become a generic management practice rather than one with moral dimensions [@feeleyNewPenologyNotes1992], and debates about imprisonment have often framed it as a technical or managerial task, rather than one infused with normative implications, as if prisons have “nothing to do with the intended delivery of pain” [@sparksCanPrisonsBe1994, p. 24].

Sparks’s [-@sparksCanPrisonsBe1994] proposal to “re-moralise” our understanding of imprisonment has been fruitful. A significant branch of scholarship now addresses normative matters regarding penal legitimacy, focussing especially on prison order and “moral performance” [@sparksPrisonsProblemOrder1996; @lieblingPrisonsTheirMoral2005]. Such studies have explored the forms of power that prisons impose, the values by which they operate, and the ways prisoners are treated as moral agents. Collectively, they contribute to broader debates about the extent to which, given the highly unequal distribution of power within prisons, imprisonment is morally defensible. Much less has been written about the other dimension of imprisonment that distinguishes it from “ordinary administrative activity” [@sparksCanPrisonsBe1994, p. 24]---that is, the fact that it is imposed upon people in response to legal and moral breaches that are of meaning to their perpetrators, and which therefore provide the animating force for the way the prison operates on them.

Our aim is to develop this branch of thinking. We agree with Sparks that justifications for punishment must be compelling, and should take account of what imprisonment is like empirically---that is, what prisons do and how they are experienced. But we see merit in shifting the focus from power and order to the offence itself: how it is embedded in the act, imposition and experience of imprisonment. This focus allows accounts to be more descriptively faithful, while also generating stronger theorisations of imprisonment. These, in turn, allow us to participate more effectively in discussions about its purpose.

We begin by examining how the offence has featured in prison scholarship---initially as a blunt or latent classificatory variable, but increasingly as something of institutional, social or subjective importance. We reflect on why prison researchers have tended not to ask prisoners about the meaning of their offence, or to centre it analytically. We then use three case studies to demonstrate how attending to the offence illuminates what prisons *are like*, what they *do*, and what they are *for*. Our aim is to explore morally-infused issues that are highly salient to how prisoners experience imprisonment, their orientation to the authorities, their reception of forms of moral communication, and broader questions about penal legitimacy.

# Literature review

Laursen and Mjåland [-@laursenAbsentpresenceOffencePrisons2025] recently described the offence as an “absent-presence” in English and Norwegian prisons: absent, in that their participants felt perplexed by the absence of meaningful communication about it, and yet present, in that a conviction was the one characteristic they shared. Our contention is that this characterisation also largely holds true for the sociology of imprisonment. We build on it by suggesting that the offence’s role in theorising prisons requires reassessment.

Influential early texts acknowledged offences, but did so mainly to construct analytical groupings---Schrag [-@schragLeadershipPrisonInmates1954] found that first-time and non-violent offenders more readily resisted “prisonisation” [@clemmerPrisonCommunity1958], while Irwin and Cressey [-@irwinThievesConvictsInmate1962, p. 141] distinguished between how professional “thieves” and state-raised “convicts” adapted to the sentence. In both examples, the goal was to theorise adaptative styles via categories derived from conviction types and criminal orientations; neither explored how members of these analytical groupings reflected upon the meanings of their convictions. A similar approach persisted in later texts concerned with prison order, where the offence continued to feature primarily as a classificatory variable. For example, Jacobs [-@jacobsStatevillePenitentiaryMass1977, p. 159] noted that an offence-based status system at Stateville had been replaced by a “balkanized” one based on racial and gang affiliations, while Flanagan [-@flanaganCorrectionalPolicyLongTerm1982, p. 83] suggested murderers were often “essentially noncriminal”, and thus distinct from the broader prisoner population.

Twentieth-century prison research features some exceptions to this pattern, most prominently the moral distinctions made by prisoners and staff regarding sexual offences, including their low status within prisoner hierarchies [@cohenPsychologicalSurvivalExperience1972], the intensified staff control to which they are subjected [@sparksPrisonsProblemOrder1996] and the increased isolation, guilt and shame they experience [@sapsfordLifesentencePrisonersDeterioration1979]; indeed, @mathiesenDefencesWeakSociological1965 suggested that “censorious” approaches to authorities could be a way of adapting to sentiments of guilt. In *Psychological Survival*, @cohenPsychologicalSurvivalExperience1972 addressed guilt and shame only in relation to their typological 'sinners’ (men convicted of sexual offences). Yet Fielding and Fielding's [-@fieldingResistanceAdaptationCriminal2008] re-analysis of their archived materials uncovered these emotions across the sample. The Durham prisoners felt safe to surface these emotions in Cohen and Taylor’s classroom “without worrying about being evaluated” by the authorities [@fieldingResistanceAdaptationCriminal2008, p. 90]. Moral reflection was thus occurring, unprompted by institutional attempts to induce it, and unnoticed by sociologists more interested by authority relations.

Latterly, prison researchers have begun addressing these issues overtly, recognising increasingly how the offence shapes how prisoners experience punishment, understand themselves, and engage in ethical self-formation. Growing attention to offence narratives and prisoners' interiority partly reflects shifts in penal power. In England & Wales, and many other jurisdictions, prisons have become “tighter” [@creweDepthWeightTightness2011; @creweTightnessRecognitionPenal2021]. Prisoners’ narratives---particularly those relating to their offending---have become objects of discipline. Offending behaviour programmes and risk assessments structure progression and release decisions, and construct prisoners by reference to their offences [@foxChangingViolentMinds1999; @lacombeConsumedSexTreatment2008]. Meanwhile, sentence inflation has intensified retributive severity for some categories of offending [@pina-sanchezMeasuringSentenceInflation2025].

Perhaps not surprisingly, then, researchers have become more interested in questions of responsibility and ethical status---or, the transmission and reception of censure. @creweLifeImprisonmentYoung2020 [p. 137] found that most life-sentenced prisoners experienced their offence as “unambiguously shameful”; @irwinLifersSeekingRedemption2009 [p. 43] documented an “awakening” process whereby lifers came to “fully appreciate” that something had been “fundamentally wrong with their former behaviour” [cf. @schinkelBeingImprisonedPunishment2014; @herbertTooEasyKeep2019]. Meanwhile, narrative criminologists have shown that prisoners shape their offence stories to “recreate and reposition themselves as particular kinds of subjects” [@ugelvikPrisonersTheirVictims2012, p. 261-2], to retain moral value despite discrediting convictions, asserting masculine legitimacy by denigrating peers convicted of sexual offences [@ugelvikRapistProperCriminal2015]. @ievinsNobodysBetterYou2015 suggest that the targets of such exclusion overlook the convictions of others to reduce the salience of their own.

Recent research has noted that factors including gender [@creweGenderedPainsLife2017], age [@tynanYoungMensExperiences2019], and offence type [@jarmanOnlyOneWay2020] shape the ethical implications of a murder conviction. Men convicted of murder in different circumstances hold varying attitudes about what was wrongful in their actions, while the narrative impact of sentences varies with age at conviction, because of the different ways the sentence impacts life trajectories [@jarmanMoralMessagesEthical2024]. While many of these examples focus on lengthy sentences and serious offences, there is also some evidence that repeated short sentences prompt reflections on the futility of lives blighted by punishment, perhaps because the low seriousness of any individual offence stands in such contrast to the accumulating harms of punishment [@armstrongPersistentPunishmentUser2013; @schinkelPersistentShorttermImprisonment2021].

Elsewhere, drawing on normative penal theory [especially @duffPunishmentCommunicationCommunity2001], prisons have been conceptualised as sites of (often oblique) moral communication. @schinkelBeingImprisonedPunishment2014 suggests that prisoners do not receive the censure that sentencers intend to convey, while @ievinsStainsImprisonmentMoral2023 examines how prisons “stain” men convicted of sexual offences. Research with people imprisoned for homicide in Argentina [@dimarcoHomicideTurningPoint2022] and England [@jarmanOnlyOneWay2020] questions whether moral reflection inevitably produces remorse or expressions of responsibility have any stable meaning. Elsewhere [@daganRetributiveWhisperCommunicative2015; e.g. @creweTightnessRecognitionPenal2021; @ievinsAuthoritarianExclusionLaissezfaire2021], risk management practices are treated as a vector for official communication about the offence. “Lateral” forms of communication among prisoners, and unintentional messages by staff, are also analytically important [@ievinsPerfectlyIndividualizedConstantly2020; @kotovaNavigatingMoralDimensions2022]: a reminder that censure can be informal and unintended. Meaningful reflection on the offence seldom occurs quickly [@irwinLifersSeekingRedemption2009; @creweLifeImprisonmentYoung2020], and is often catalysed when a life after prison becomes imaginable, so that engagement with institutional demands (e.g. for ‘insight’ into the offence) is more strongly incentivised [@odonnellPrisonersSolitudeTime2014; though see also @seedsHopeLifeSentence2022 on 'deeper' forms of hope].

Adapting Laursen and Mjåland’s [-@laursenAbsentpresenceOffencePrisons2025] term, then, in much twentieth-century prison research, the offence was *latent*-present: understood to signify types of people, but seldom analysed either as a moral category forced onto individuals, or as an act holding ethical significance for the perpetrator. Recently, though, the offence has become a more explicit focus. Attention has shifted towards the *subjective meanings* of moral and legal labels---that is, how it might feel to be (or be held) responsible for a specific offence, how an individual might navigate such matters, and how this might alter their broader prison experiences. The shift invites us to consider prisons not simply as social settings producing psychological adaptations, but sociologically: as places where the personal and cultural meanings of wrongdoing are negotiated.

An empirical focus on the moral meaning and effects of imprisonment also brings into view normative discussions about the justification and justice of punishment. Given that, in most countries, imprisonment is the archetypal form of punishment, and prisons so often treat reflection on and ‘insight’ into the offence as a desirable response [@paratoreInsightLifeCrimes2016; e.g. @shammasPerilsParoleHearings2019; @dykeHowParoleBoard2020], a shift towards questions of purpose is an important step, since the *kinds* of insight which might be expected vary accordingly. Communicative theories of retributive punishment [@duffPunishmentCommunicationCommunity2001; @brownleeOffendersPartDialogue2011] can help here, since they insist that punishment expresses communal values and should respect offenders’ moral agency. Although moral censure may be distorted by imprisonment, or go unnoticed [@schinkelBeingImprisonedPunishment2014], our contention is that focusing on imprisonment’s morally communicative aspects adds a great deal to our understanding of penal legitimacy. This makes it all the more striking that the offence features so little in conventional prison scholarship.

# Researching the offence

Within prisons, someone lacking a story about why they are there, or unduly defensive when asked, is considered by other prisoners to be rather suspect [@crewePrisonerSocietyPower2009]. Yet the convention among prison researchers[^1] is that it is generally inappropriate or inadvisable to ask an incarcerated person directly about the details of their offence.[^2] This norm is framed primarily as an ethical imperative. Asking people what they did to be there---it is suggested---risks pathologising or re-traumatising them, compounding their stigmatisation, or conflating the person with their conviction. Alternatively, it taints the interviewer’s ability to remain non-judgmental [@stevensOffenderRehabilitationTherapeutic2013]. Thus, while populist discourses construct prisoners as *bad people*, prison researchers have tended to swerve or reject such judgments. If anything, the norm has been to express sympathy or identification with prisoners (i.e. as victims or anti-heroes), especially in critical scholarship, where judgment is directed towards the carceral institution rather than incarcerated people, thus removing the offence as an object of analysis.

This tendency also reflects the longstanding disciplinary parameters of prison sociology. While normative issues---such as, guilt, culpability and moral communication---play important if varied roles in penal theory, prison sociology has tended to see them as irrelevant [@schinkelBeingImprisonedPunishment2014; though see @ievinsStainsImprisonmentMoral2023; @jarmanMoralMessagesEthical2024]. To some degree, this position is defensible. As we note above, offence *type* has been associated with prisoner hierarchies and orientations to authority, but offence *reflections*, while sometimes present in studies of life *after* prison [e.g. @liemLifeImprisonmentReentry2016] are somewhat immaterial to many core topics in prison research. When researchers study prisoner social relations or penal order, it can feel digressive to discuss prisoners’ thoughts on whether the penalty fits their crime, or their internal battles to maintain a self-image of respectability.

Relatedly, interest in prisoners’ interiority has generally been subordinate to interest in their *social practices*. Canonical texts [@sykesSocietyCaptivesStudy1958; @mathiesenDefencesWeakSociological1965; e.g. @jacobsStatevillePenitentiaryMass1977] have generally been concerned with theorising social structures and institutional processes, rather than prisoners’ reflexive existence. Methodologically, the semi-ethnographic emphasis on “where the ‘action’ is” [@mcdermottMindGamesWhere1988]---wings, yards, workshops, and other collective areas---may have missed existential or ethical reflections occurring in more private spaces. Most obviously, cells are where many prisoners spend much of their time, affording headspace for internal reflection. Yet though the offence may be more present in such spaces, methodologically they are fairly inaccessible, and practices of contemplation and rumination occurring there leave no obvious trace.

Even so, our conjecture is that many prison scholars hear reflections on the implications of prisoners’ offences and convictions but exclude these from their accounts. We find it hard to imagine that anyone who has interviewed people convicted of serious sexual or violent offences has not been presented with narratives of regret, indignation, and other moral emotions. Indeed, in our experience, many people convicted of more minor offences also offer a moral narrative about the events leading to their current circumstances: why they burgled houses, or dealt drugs, for example. Our view is that such accounts and reflections should be taken seriously and examined empirically, without undue moralisation. It might be possible to interpret prisoners' accounts as neutralisations or rationalisations, but this framing presumes that the criminal conviction contains a factually accurate, complete, and morally authoritative version of events. Moreover, if violence and other forms of crime are communicative, *not to* enquire about them means not taking seriously what they were attempting to express; at the least, it seems just as disrespectful to deflect any attempt to discuss the offence---the very reason why the person is there---as it is to probe into it.

The three projects drawn on in our case studies [see @creweLifeImprisonmentYoung2020; @creweNordicPenalExceptionalism2023; @jarmanMoralMessagesEthical2024 for methodological details] involved lengthy interviews, some conducted over multiple sessions or following a sustained presence in the prison. While these projects varied in their explicit focus on offences, all employed semi-structured interviews that allowed participants to narrate their experiences of imprisonment and relationship to their convictions. In all three, we deliberately asked some questions about the offence and/or conviction, and how they impacted people’s sense of self, the prison’s social world, and the extent to which they were a target of power. All of us felt that participants’ willingness to discuss these matters required us to avoid displaying the shock or revulsion some of them anticipated (though for researchers to become completely dispassionate might also be unwise). Existing work on the ethical considerations involved in interviewing people convicted of serious, and particularly sexual, crimes often focuses on the converse moral threat: collusion with morally unacceptable viewpoints or factually incorrect accounts [@waldramEverybodyHasStory2007; @blagdenChallengeConductingQualitative2010; @digardSexOffendersTheir2010]. We have discussed these dilemmas elsewhere [@ievinsStainsImprisonmentMoral2023, p. 33-36; @jarmanMoralMessagesEthical2024, p. 66-77], but they take a specific form when the focus of the research project is not what actually happened, but how people reflect on it and its role in the prison. Researchers should neither entangle themselves in inappropriate side-taking, nor mislead participants by implying greater sympathy than they feel [@malcolmJournalistMurderer1990; @creweClosenessDistanceHonesty2015]. However, that need not stop us from recognising the continuing effect of the offence in their lives, via the sense they make from it.

Our first case study derives from ethnographic research in a medium-security English prison for men convicted of sex offences, part of a larger research programme comparing imprisonment in England & Wales and Norway [see @creweNordicPenalExceptionalism2023]. Extended observation and 45 interviews (averaging three hours) explored how penal power shapes social relations, with explicit attention to shame, guilt and conviction legitimacy.

The second case study comes from an interview-based study of 146 men and women serving life sentences for murder, convicted aged 25 or under [@creweLifeImprisonmentYoung2020]. Interviews, averaging two hours, did not actively seek information about the specifics of the index offence, but these were often volunteered, and the interviewers engaged responsively when this happened, exploring orientations towards the offence, conviction and sentence.

The third case study is drawn from a study of 48 life-sentenced men in two English prisons: a closed long-term prison, and an open prison tasked with resettlement and release [@jarmanMoralMessagesEthical2024]. Despite all sharing a murder conviction, participants were otherwise diverse: aged from their teens to their seventies at conviction, imprisoned for between two and 37 years, with varied offence and pre-prison circumstances. Interviews (averaging almost four hours) were supplemented by document analysis.

# Case studies and argument

Our case studies are intended to be illustrative. We have selected them because they offer analytical clarity. They highlight three ways in which considering the offence helps us more fully theorise the prison: specifically, what prison is *like*; what prisons attempt to *do*; and what prisons are *for*.[^3]

The first dimension---*what prison is like*---examines the phenomenological and social consequences of the offence. It attends not only to objective features of the penal setting, but also what prisoners find subjectively important. For example, the ‘moral weight’ [@hulleyMoralWeightMurderforthcoming] and personal significance of a particular offence might generate distinct patterns of self-understanding, adaptation, and social interaction. All of these are significant topics in orthodox prison sociology; but we believe they are mediated by reflection upon the offence and/or conviction and what they mean, subjectively. Indeed, our contention is that these can be *the* major mental preoccupations for some people.

The second dimension examines *what prisons do*, in communicating with people about and attempting to mould their reflections on their convictions. Here, we ask what messages prisons transmit about particular offences, and how these messages are delivered. This encompasses both explicit communications, such as those occurring via therapeutic intervention or risk assessment, and implicit ones embedded in everyday practices and interactions. It also involves material practices of treatment and intervention, from staff conduct to direct engagement with prisoners’ offending behaviour. Theoretically, this raises questions about how prisoners navigate and interpret the often oblique and inconsistent messages they receive and the various forms of institutional action to which they are subjected.

The third dimension examines what *prisons are for*. This is a question of purpose and aims, and situates moral communication within a wider context. It therefore connects to how we theorise prison legitimacy, and to broader questions about whether prisons deliver something more salutary than mere pain, and how their harms can be justified. These questions are shaped by the rationale(s) used to defend the use of imprisonment, and the extent to which their aims are realised. Different penal logics---whether retributive, rehabilitative, deterrent, or incapacitative---imply different messages about wrongdoing. In practice, such discourses co-exist within the same institutional context, producing tensions and contradictions. Still, both the content of censure, and the efficacy of prisons in delivering it, are amenable to empirical investigation, in ways that place the offence---how it is understood by both the individual and the institution---centre-stage.

## Mick

Mick,[^4] held in a medium-security prison for men convicted of sex offences, was heavily involved in the informal prisoner economy, and frequently got into bitter, public arguments with prison staff. When interviewed, however, it became clear that this defiant public persona stemmed from his complicated relationship to his imprisonment. When Mick was a child, he was persistently abused by his stepfather, and coerced into raping his younger brother. Years later, reported his stepfather to the police, but was ultimately prosecuted for acts which he said he had committed under duress as a child. He was found guilty, and sentenced to three and a half years in prison.

Mick’s anger had its “root” in “what happened when I was a kid”, but since then “everything else just piled on top of it”. He had flashbacks of “what happened [...] every night before I go to bed”, and had “really bad trouble sleeping”, and would lie awake thinking about “just everything that happened, what’s going on, the fact that I’m here now and it really shouldn’t be me”. Now, he was “still living around paedophiles again, like I did for most of my childhood”. He was attuned to and disgusted by signs of inappropriate sexual behaviour from prisoners and staff, but the depth of his rage came from what his fellow prisoners represented and reminded him of: “I’m angry at all these people who haven’t done nothing to me but I just see them as 1,100 of my step-dad and I can’t get that out of my head”.[^5]

He maintained emotional distance, engaging in shallow forms of sociability for trading purposes, but had no friends on the wing, and preferred solitude:

  > I can’t wait for that door to close of an evening to get away from it all. [...] I have to socialise to a certain degree during the day, but it isn’t really socialising. It’s getting what I need from these people. [...] I put this fake persona on of happy, laughy, jokey, “Oh, you alright?”

He lied to other prisoners about his conviction, telling them he had been falsely accused of sexual assault by his girlfriend, because he couldn’t bear the idea of telling someone the truth and them turning out to be a “raging paedophile”, and did his best to “switch off” to conversations about offences. Nevertheless, he maintained there was a moral difference between him and his apparent peers. He described himself as infuriated when he heard other prisoners claim that “we’re all in the same boat here”: “I think, ‘We’re not in the fucking same boat here.’ We might have all ended up on the same desert island but fuck me; I rowed here in a completely different boat to you.”

His relationship with officers was actively fractious---“[they] piss me off on a daily basis”---and he was especially censorious towards those who engaged in, or did not prevent, inappropriate sexual behaviour. He complied when he wanted to, but cared too little about the prison’s incentives for them to work on him:

  > I don’t like playing the victim, but, I feel really wronged for being here, and feel like the right person hasn’t been brought to justice, so therefore, give me a DVD player, it’s not going to make me feel any better. It would kill some time but nothing that they can do or give me is going to make me feel, “Oh, it’s okay being here, isn’t it?” Are they going to put [step-dad] in prison and make him suffer for what he’s done? No, they’re not. Well, then I don’t want to comply with your shitty regime.

Nevertheless, he was open, at least in theory, to engaging in therapeutic work. He was unwilling to participate in the Sex Offender Treatment Programme, which involved discussions of the offence itself---“there’s no way I’m sitting in a room listening to ten fucking paedophiles talking about what they’ve done”---but he wanted to do “anything that will help me deal with this”. In his previous prison, he had seen a counsellor, who had helped him begin to “come to terms with the fact that maybe I’m not fully to blame here”. In his current prison, he received no therapeutic or offence-related support, and could not even be properly risk assessed because of the age at which the offence was committed.

Despite his significant frustration with prisoners and prison staff, Mick insisted that what really mattered was the damage that had been done to his family. Prison might be difficult to deal with, but it was bearable. What was harder to cope with was the fact that he was unable to contact his brother: “I can deal with being in here. I can deal with this shitty routine and the knobhead prison officers and fucking raging paedophiles and stuff that are around but the one thing I can’t deal with is that.” Alongside his real anger at the injustice of his situation were profound feelings of guilt about what had happened to his brother. Being in prison, and the conviction that came with it, was a deeply painful because it was unfair and staining, but also because it confirmed what he feared about himself. He had always believed “that I am a horrible person and that I am a bad person because I didn’t protect my brother”, and the conviction “just concretes what I thought of myself [...] and makes it true. I think that it’s broken me as a person.”

## Chris

Chris was an intimidating presence: muscular, taciturn and with an air of defensive intensity. He described relatively little about his childhood, but said he had been exposed to considerable physical and sexual violence. As a result, he had been an angry young man who had resorted to drugs to cope with and mask his emotions: “All my childhood was drugs”. He had been convicted of a murder with a sexual component, and was saturated with feelings of shame: “It eats at me every day”. After his arrest, he had pled guilty immediately and made no attempt to minimise his culpability. Sentiments of remorse and self-loathing dominated the interview, just as they governed his experience of imprisonment

Chris was a “loner”, with just a couple of loose associates, whom it had taken him months to first talk to. He did not need other people, he said, and struggled with social situations: “in an empty room it’ll feel crowded to me, because I’ve got so much going on upstairs”. He had no involvement in illicit activity, having given up drink and drugs because of their role in his offence: “As soon as I committed my crime my head went...gone. I never touched anything again”.

His coping mechanisms were also relatively solitary, shaped by his feelings about his offence. He exercised compulsively, using a rowing machine to “take my mind off it” and ensure that, at the end of each day, he was too exhausted to ruminate on his crime. Day-to-day, he was preoccupied with obtaining sufficient sleep and protein to help him build muscle. Alongside physical activity, Chris liked to paint, which he said was a way of processing and expressing his feelings. He had converted to Christianity during his sentence, and this provided further emotional relief: “that’s what I was looking for, peace and forgiveness”.

Despite his psychological torment, Chris had not asked for help from staff, stating that he had no faith that they would want to support him: “It’s a bad crime [...] why would you want to help a convict who’s committed a serious crime?” His declaration that he did not trust staff, that it was “us and them”, and that he did not need any help betrayed an underlying sense that he was unworthy of support and humanity. He assumed that anyone who read details of his offence in his file would hate him, and therefore pre-empted negative responses by telling staff: “You don’t even have to try with me, just leave me be”.

Chris’s orientation to his sentence was normative but disengaged acceptance. He experienced both the sentence and his punishment as entirely legitimate. Yet the prison was virtually irrelevant, either as a communicative institution or as a site of intervention. That is, given his profound feelings of shame, external moral censure was redundant: “I punish myself more than any of these can punish me”. He harboured no feelings of resentment about his sentence length, commenting on several occasions that he “deserved what I got”. This sense that he warranted punishment---and that he was morally worthless, almost a non-person---was expressed in a general fatalism about his treatment (“they’re here to punish us [and] I don’t mind them punishing us”), the passage of time (“every day comes, every day goes---it’s all part of the punishment”), what was written about him on file, and his progression through the system. “I just go with the flow”, he commented: “whatever happens, happens. I just see it as it’s all part of the sentence”. He declared himself unconcerned by how his time in prison might affect him - “Like I say, it is what it is”---and, due to the nature of his offence, felt he had no right to judge others.

Chris did not believe he could ever move on from what he had done. He was haunted by intrusive recollections of his offence, and, when asked about the hardest time during his sentence, said: “Maybe just the nightmares, stuff like that. [...] I wouldn’t say anything else has caused a problem”. He had not yet undertaken any courses because he felt he would not be able to cope with having to think about his own crime or with exposure to “graphic detail” about other people’s offences: “when people are talking about their crimes I’m seeing their crime in my head, and it kills me. [...] I can see my own, I don’t want to see theirs, you know”. Emotionally, he was extremely tightly wound.

Despite feeling he could never “put it right”, Chris described practices consistent with a desire to demonstrate ethicality. For example, although he generally distanced himself from prison officers, he sometimes informed them about issues and potential incidents on his wing. His justification (for what other prisoners would consider “snitching”) was to avert it being on his conscience were someone to get hurt. Likewise, he reported getting involved in disputes not out of loyalty to others, but because he wanted to avert violence: “if anyone tries to attack anyone, then that’s when I go in, because silliness comes of silliness”. Despite this drive to compensate for his offence through everyday moral action, he described himself as having no goals and said he was living day-to-day, without contemplating the possibility of release: “I’m not really interested at the minute”.

## Nicholas

Nicholas had recently arrived in an open prison, having spent many years in maximum-security custody. Though he had previously mistrusted staff and feared other prisoners, his attitudes now were noticeably positive. For example, he remarked that he had been “very, very, very, very lucky” in the staff who had worked with him, and described sharing jokes with officers. At the system’s shallow end, he was struck by the degree to which the “bond between [prisoners in] closed conditions” had been superseded by more individualised thinking, as they turned towards resettlement goals and the post-prison future. Indeed, his own mind was increasingly doing the same:

  > Am I going to have a good quality of life if I am released next year? I will be [in my forties] [...] Am I going to have enough time to get married? Am I going to have enough time to have kids? [...] I would never, ever treat my wife or children the way that my dad treated me.

In childhood, Nicholas had suffered physical, sexual, and emotional abuse inside and outside the home. His first attempt to talk about any of this had been in the context of a police interview: he offered a partial disclosure to the detectives who would shortly charge him with murder, but no further action resulted. Two decades on, he verbalised the emotions he had once acted out through violence:

  > There was so much aggression when I finally committed those offences. But I think [it was] loneliness [that] resulted in that anger [...] Not being seen, and then suppressing feelings about that, and then continuing not to be seen, just getting sort of angrier and angrier about it [...] I was emotionally withdrawn. Lonely, confused. And still very young [...] There wasn’t that feeling of sadness. Or shame. Or fear [...] There was no attachment to it or to the consequences of it at all.

Nicholas saw that the gravity of his actions warranted censure. But at the time, his disclosure having resulted in no further action, he reverted outwardly to detachment and denial. As a result, he had spent the first decade or more of the sentence living in two parallel realities. In one, he had learned to cope and adjust. In young offender institutions, terrified of wing life, he had stayed in his cell whenever possible. Later, in adult prisons, things “started to move upwards”. Yet this outward adaptation had masked his inability to accept what he had done. There was no *inward* adjustment, still less any reconciliation, with the formal responsibility imposed by his conviction. He could only retreat into fantasy: “It was very easy to put myself [...] somewhere else [...] to blank out what I had done”. Eventually, however, the dissonance between inner and outer life more and more resembled a problem:

  > If you allow yourself to be switched off 24 hours a day from reality [...] eventually it gets to an extent where you find yourself too far gone. It becomes hard to bring yourself back to reality. I don’t think that that changed for me for [more than ten years].

Thus, while a process of adaptation appeared to be ongoing, something else more personal and related to the offence was *also* shaping Nicholas’s engagement with the sentence:

  > I wasn’t in healthcare [anymore]. I was on normal location. I wasn’t as medicated [...] I was comfortable on the wing, around people [...] [But] I still had that ongoing battle, sort of thing, with that detachment. [...] I was just, you know, fighting with myself on a day-to-day basis and just going through knowing that [what was] in my mind was something else compared to what was going on for real.

The challenge he described was to find some way to account to others---not just to himself---for his conviction. Nicholas’s disclosures to detectives might be seen as an early, halting attempt. He revisited the disclosures during several years in a prison unit whose therapeutic ethos, he said, meant there was “no way of hiding”. It offered a framing of his story which omitted neither his offending nor the soil it had grown in:

  > It enabled me to see [...] how those childhood events [...] shaped that person I’d become. [...] It’s hard to sit there, in a group, and see something being read out on a board, in front of everybody, and actually say, “Yes, that person that’s on there that you’re reading out is really horrible. [...] That’s not a nice person. [...] But that person is me.”

Nicholas expressed happiness at his formal progression to the verge of release. Along with his improving family relationships, he counted it as a real positive. But the deeper gain, he made clear, was a more “normal” relationship with himself:

  > *Have you gained anything that matters to you since you’ve been in prison?*
>
  > Yes. My religion. [Long pause] My family. Myself.
>
  > *You’ve gained yourself?*
>
  > Yes. Going along those lines that... I matter as well. [...] That is what I’m referring to. [...] After I went to the [therapeutic] unit [...] it was all about me, and about accepting me for who I was.

Although he was pointing here to subjective benefits, Nicholas’s orientation was far from solipsistic, and in fact evinced a form of accountability. He believed victims should be able to demand and receive explanations, and regretted that the parole process had not afforded opportunities for such dialogue:

  > I also look at it from other people’s point of view. [...] My victim’s family [...] has that involvement with the victim liaison officer. They went to my hearing when the parole [board] sent me to open conditions. So, although they don’t have contact with me, and they never probably will have contact with me because they don’t wish to know me [...] they still don’t know why I’ve done what I done.

For Nicholas, then, the offence was not a static fact to be managed or concealed, but a living problem requiring ongoing moral work; it shaped, but also exceeded, questions of adjustment or compliance.

# Discussion

Returning to our framework, our first contention is that attending to the offence helps us to better grasp *what imprisonment is like*, deepening our understanding of conventional preoccupations of prison sociology such as adaptation, compliance, staff-prisoner relationships, and prisoner social relations. In conventional accounts [@sykesSocietyCaptivesStudy1958; @crewePrisonerSocietyPower2009; @skarbekPuzzlePrisonOrder2020], social dynamics are produced by prisoners’ efforts to meet urgent and significant needs. They engage with each other to mitigate deprivations, secure their safety, defend their interests and protect their identities. These efforts might not be conscious and deliberate, as such, but are predictable within a paradigm in which the solutions offered through social interaction impel action in almost mechanical ways. We find this analytic framework generally persuasive, yet also somewhat reductive, based on its impoverished understanding of the moral and psychic drives that also generate personal action.

To develop this point, the primary preoccupation for many prisoners may be psychological rather than social survival: an *internal* struggle relating to the moral implications of serious offending. Grasping *what imprisonment is like* for Mick, Chris, or Nicholas---what dominates mental headspace---requires placing the offence centre-stage. For all three, the importance of the prisoner social world is subordinate to the task of coming to terms with feelings of shame and bewilderment. Indeed, Nicholas’s social practices alone might mislead us about what it is to be convicted and imprisoned. Apparent outward adjustment might conceal inward turbulence.

This contrast between outward and inward realities enriches our understanding of topics of longstanding interest to prison sociologists. For example, staff-prisoner relationships have typically been understood through criminal codes, authority orientations, and power disparities [@sykesSocietyCaptivesStudy1958; @irwinThievesConvictsInmate1962; e.g. @cohenPsychologicalSurvivalExperience1972; @drakePrisonsPunishmentPursuit2012]. Yet Mick and Chris show that prisoners who distance themselves from officers (or other staff) might have in mind how those staff members represent certain feelings about their convictions, or how the criminal justice system has interpreted their acts. Prison staff do not simply represent state repression [@jacobsStatevillePenitentiaryMass1977; e.g. @irwinPrisonsTurmoil1980], nor act simply as agents of discipline and control [@carrollHacksBlacksCons1974; @drakePrisonsPunishmentPursuit2012]. They also symbolise *punishment*: if prisoners perceive staff to be the deliverers of a deserved (or harsh) penalty, their orientations towards them may be altered as a result.

Levels of compliance, including engagement with offending behaviour programmes, are likewise shaped by offence-related sentiments -- hence Mick’s tense relationship with prison staff and unwillingness to conform to a regime to which he felt he did not deserve to be subjected, Chris’s general disengagement and resistance to activity that would vivify his intrusive thoughts, and Nicholas’s inability, prior to therapeutic input, to contemplate life as a free citizen who had taken responsibility for his past actions. Just as (non)compliance among prisoners can be motivated by how they feel about the legitimacy of their treatment [@sparksPrisonsProblemOrder1996; @lieblingPrisonsTheirMoral2005], so too it is shaped by how they feel about the offence for which they have been convicted.

The topic of social relations illustrates the same point. How our examples chose to interact with their peers, involve themselves in the prisoner society, or self-isolate, cannot be attributed only to the idea of ‘problem-solving’. Their choices also reflected comparative moral evaluations prompted by the offence and the conviction, as filtered through emotions like disgust (Mick), the capacity to handle ruminative turmoil (Chris), or the challenges of accounting for one’s actions to others (Nicholas). Meanwhile, conventional ‘coping mechanisms’, such as Chris’s commitment to faith, exercise and art, can be reinterpreted as ‘ethical projects’---a means to grapple with emotions summoned by the offence, not just ‘escape activities’ [@goffmanAsylumsEssaysSocial1961] or outlets for frustration [@lawsCagedEmotionsAdaptation2022].

Regarding the second dimension of our framework, considering the offence clarifies something significant about *what prisons do*. Some of their operations are directly and obviously organised around the offence, particularly when they attempt to mould how people reflect on it. This is sometimes a deliberate target of power---as when prisons seek to equip people with 'skills’ which will help them to manage their risk in future---and sometimes the basis of organisational categorisation: e.g. Mick was classed as a “sex offender” and held among people who were similarly categorised, but from whom he felt morally distinct. In other words, prisons are morally communicative institutions---a role and function which has not been properly explained in previous accounts [@schinkelBeingImprisonedPunishment2014; though see @ievinsStainsImprisonmentMoral2023].

Even when the offence is not explicitly threaded into the operations of power, the fact of being in prison, and how prisons are organised, influences how people reflect on and relate to their conviction. As our case studies illustrate, these processes differ considerably, but are key to understanding the subjective processing of moral and penal censure. Nicholas, for example, offers a rare example of a period of imprisonment facilitating what he considered a more productive relationship between himself and his offence, enabling him to “sit with” his culpability.[^6] Mick, in contrast, felt imprisonment might potentially have helped him “come to terms with everything that’s happened”, but experiences of misrecognition and unmerited punishment blocked this process. He was left oscillating between bitter resentment and profound shame, prompted by the harms for which he did feel responsible. Chris, meanwhile, assumed that the system judged him harshly, presuming this to reflect his own self-evaluation. Such was the depth of his self-disgust, however, that external engagement was neither needed nor wanted, and he could access no route by which to digest his feelings of shame.

Our case studies also illuminate fundamental tensions in how contemporary punishment actually operates, versus how it justifies itself. This unavoidably brings into view the third dimension of our framework: questions of *what prisons are for* and whether they fulfil their objectives. Seeing prisons as morally communicative institutions involves seeing that they contribute to a wider punitive ritual [@durkheimTwoLawsPenal1973], which signals disapproval and affirms values essential to collective life. One of the paradoxes of the modern prison, however, is that it takes a hitherto public and participatory procedure like punishment, and then obscures it through enclosure, bureaucratisation and legalisation [@garlandPunishmentModernSociety1990]. By considering the moral messages it conveys, however, we can cast light on the prison’s punitive functions, seeing imprisonment not as ‘an ordinary administrative activity’ [@sparksCanPrisonsBe1994, p. 24] but rather stimulating discussion about the justifications of punishment and the extent to which prisons can achieve them.

Our case studies offer evidence of problems with how individual accountability---broadly understood to mean ‘taking full responsibility for oneself and one’s harmful actions’---is pursued in practice. Advocates of different penal logics place differing weight on the goal of accountability. Some modern retributivists believe that holding people accountable for their wrongful acts, and giving them the chance to take full responsibility, is a justifiable goal of punishment [@duffPunishmentCommunicationCommunity2001; @tasioulasRepentanceLiberalState2007]; critics, on the other hand, view the pursuit of accountability as a dangerous, futile, and backward-looking overuse of state power [@vonhirschPunishmentPenanceState2005].

Chris’s and Mick’s stories illustrate some dangers of the exclusive pursuit of accountability---a goal which, with Chris, did not require punishment, and with Mick, did not tally with the moral complexity of his conviction. Nicholas, however, illustrates that, under very specific circumstances, retributive approaches might be integrated with rehabilitative ones. His therapeutic intervention allowed him to see *both* that he was culpable *and* that “I matter as well”---a form of accountability approaching what @mcneillFourFormsOffender2012 [p. 15] terms “moral rehabilitation”. It is striking that Nicholas clearly articulated concern for his victims, and expressed the view that his obligations to them were not fully discharged. Like Mick, Nicholas was troubled that his punishment denied him the opportunity to apologise to and make amends with the people he had harmed. In other words, both men suffered because their punishment felt like an incomplete ritual---at best, bringing them to the point of desiring repair, but unable to actually achieve it. These cases thus reveal how contemporary imprisonment often initiates---without completing---the moral work of censure that punishment is claimed to perform. Seen in this way, prisons thwart the punitive ritual which is claimed to justify their use in the first place.

# Conclusion

We have argued in this article that prison sociology's traditional concerns are enriched considerably by considering the offence. This is partly because such consideration illuminates, at a basic empirical level, our ability to comprehend what people in prison are preoccupied by the moral evaluations of self and others that shape their actions, and the ways they are managed and addressed by the institution: as people defined by the conviction which brought them into it. It is startling that so little prison research has closely studied these aspects of imprisonment, documenting how criminal offences, and their moral implications, infuse its lifeworld. Perhaps most centrally, we are arguing that the prison’s role *as a punitive institution* should be a much more central element of how we theorise it. Prisons deliberately impose suffering on those who are deemed to deserve it for their imputed wrongdoing. Meanwhile, in wrestling with the implications of what they have done, or are assumed to have done, those people engage in a range of ways with what it means to be punished, and---often---to punish oneself.

This interaction between institutional and individual reckonings produces much of the prison’s “moral intensity” [@lieblingEpilogueMoralEthical2025, p. 1]. Yet, as @lieblingEpilogueMoralEthical2025 [p. 2] argues, “It is one of the tragedies of the prison as an institution of punishment that its moral effects are assumed rather than empirically studied”. Some of these effects---those produced by the loss of liberty and its collateral consequences---are well documented. But the existential texture produced by “darkness, power and deprivation” [@lieblingEpilogueMoralEthical2025, p. 1] is overlain by an additional layer of moral sentiment relating to ‘the offence’. Bringing this layer into focus means participating in normative discussions: not to make declarations, necessarily, but to bring empirical complexity to an impoverished public discourse that swings between vindictive moralising (“bad places for bad people”) and naïve fantasies of rehabilitation (“using prisons to reduce reoffending”). Such representations contribute to a seriously unhelpful politics of punishment, because they “roam free in a realm of imagination and mythmaking with only the most tenuous connection to what happens inside the system” [@sparksCanPrisonsBe1994, p. 24]. Neither vindictive moralising nor rehabilitation fantasies capture the moral complexity evident in our case studies, which hint at ethical work that will often be self-initiated, incomplete, and shaped by the specific nature of the offence and its personal meaning.

Our cases---all men with traumatic childhoods convicted of serious offences---are specific, but illuminate dynamics that operate more broadly across imprisonment. People serving sentences for other kinds of crimes might reflect differently on their offence, navigate their time in prison according to quite different moral coordinates, and be addressed systemically as different kinds of moral agents. But there is plentiful evidence that people serving short sentences grapple with, and then act upon, feelings of shame, resentment and existential futility [@crewePrisonerSocietyPower2009; @schinkelPersistentShorttermImprisonment2021]. In this respect, we think our argument is applicable beyond the particular kinds of men whose testimonies we have drawn upon here. We therefore urge other scholars to study and theorise the prison with the issues we have highlighted in mind. This means moving beyond the tendency to treat offences as mere classificatory variables, recognising instead that they carry subjective meanings central to imprisonment's moral dynamics---a shift already underway but requiring fuller development.

# Authorship roles {.appendix}

This article builds from conversations which developed over several years. We would find it difficult to specify precisely which author contributed which parts of the argument, and all authors contributed equally overall. Author names appear in reverse alphabetical order by surname, to avoid replicating academic seniority based on the alphabetical positioning of our surnames.

<!-- # Acknowledgements {.appendix}

[Something…] -->

::::: {.content-hidden when-format="html" unless-format="revealjs"}
{{< pagebreak >}}

# References {.unnumbered}

::: {#refs}
:::
:::::

[^1]: There is, of course, a tradition of researchers interviewing people in prison *specifically about their offending* and the nature of crime and criminality, but we count this as research done within prisons rather than research about imprisonment.
[^2]: The norm is often not explicit in methodological reflections, but have discussed it with many other prison researchers and are confident that how we have articulated it here is consistent with the messages that most junior scholars absorb.
[^3]: Each case study touches on different elements of this framework i.e. our aim is not to illustrate the same points in three different ways.
[^4]: All names are pseudonyms, and we have changed any potentially identifying features.
[^5]: 1,100 refers to the population of the prison where Mick was held.
[^6]: An important precondition for this change was its setting: a prison unit characterised by supportive, and yet demanding, forms of intervention.
